[package]
name    = "searchspot"
version = "0.1.0"

authors = ["Giovanni Capuano <webmaster@giovannicapuano.net>"]
license = "BSD-2-Clause"

[dependencies]
rs-es           = "0.2.5"
rustc-serialize = "0.3"
chrono          = "0.2"
iron            = "0.3"
router          = "0.1"
logger          = "0.0"
params          = "0.2"
toml            = "0.1"
lazy_static     = "0.2"
maplit          = "0.1"
oath            = "0.1"
log             = "0.3"

[lib]
name = "searchspot"
path = "src/lib.rs"

[[bin]]
name = "searchspot"
path = "src/main.rs"
doc  = false

[target.heroku]
version = "stable"
