[package]
name    = "searchspot"
version = "0.2.0"

authors = ["Giovanni Capuano <webmaster@giovannicapuano.net>"]
license = "BSD-2-Clause"

[dependencies]
chrono          = "0.2"
iron            = "0.3"
router          = "0.1"
logger          = "0.0"
params          = "0.2"
lazy_static     = "0.2"
maplit          = "0.1"
oath            = "0.1"
serde           = "0.7"
serde_json      = "0.7"
serde_macros    = "0.7"

[dependencies.toml]
version  = "0.1"
features = ["serde"]
default-features = false

[dependencies.rs-es]
version  = "0.3.4"
features = ["nightly_without_ssl"]
default-features = false

[lib]
name = "searchspot"
path = "src/lib.rs"

[[bin]]
name = "searchspot"
path = "src/main.rs"
doc  = false

[target.heroku]
version = "1.9.0"
